Repository utaipei-sa/api.reserve.utsa, pull requests merged in 2024-08, with the labels that each got.

#87 ci :add ci
  .github/workflows/lint.yml
  package-lock.json
  package.json
  routes/reserve/get_space_available_time.js
  routes/reserve/put_reservation.js
Labels: enhancement

#68 PUT /reserve/{reservation_id} 更改預約資料
  docs/openapi.yaml
  models/crud.js
  routes/reserve/index.js
  routes/reserve/post_reserve.js
  routes/reserve/put_reservation.js
  routes/reserve/put_reserve.js
  utilities/reserve/split_item_reservation.js
  utilities/reserve/split_space_reservation.js
  utilities/reserve/validate_item_reservation.js
  utilities/reserve/validate_reservation_info.js
  utilities/reserve/validate_space_reservation.js
Labels: Feature

#89 Feat: 新增驗證修改刪除預約紀錄 email
  routes/reserve/delete_reserve.js
  routes/reserve/get_reserve.js
  routes/reserve/patch_verify.js
  routes/reserve/post_reserve.js
  routes/reserve/put_reserve.js
  utilities/email/email.js
  utilities/email/sendReservationEmail.js
  utilities/email/template_utils.js
  utilities/email/templates/cancel_reservation.js
  utilities/email/templates/check_email_template.js
  utilities/email/templates/new_reservation.js
  utilities/email/templates/success_email_template.js
  utilities/email/templates/update_reservation.js
  utilities/email/templates/verify_reservation.js
Labels: Feature

#95 Fix/CodeQL
  app.js
  package-lock.json
  package.json
  routes/reserve/get_item.js
  routes/reserve/get_item_available_time.js
  routes/reserve/get_reserve.js
  routes/reserve/get_space.js
  routes/reserve/get_space_available_time.js
  routes/reserve/patch_verify.js
  routes/reserve/post_reserve.js
  routes/reserve/put_reserve.js
  utilities/email/template_utils.js
  utilities/reserve/validate_item_reservation.js
  utilities/reserve/validate_space_reservation.js
Labels: Refactor, Improvement
