Repository utaipei-sa/api.reserve.utsa, pull requests merged in 2024-11, with the labels that each got.

#120 Fix: wrong openAPI path
  routes/reserve/get_reserve.js
Labels: patch

#119 Revert "Add Google login API & JWT authorization"
  .env.template
  app.js
  package-lock.json
  package.json
  routes/auth.js
Labels: invalid, minor

#123 Ci: linter git action fix
  .github/workflows/lint.yml
Labels: bug, patch

#122 Fix: change status code from 200 to 500 when email fail to send
  routes/reserve/delete_reserve.js
  routes/reserve/patch_verify.js
  routes/reserve/post_reserve.js
  routes/reserve/put_reserve.js
Labels: patch

#121 Fix: available time query validator bug
  routes/reserve/get_item_available_time.js
  routes/reserve/get_space_available_time.js
  utilities/input_format.js
Labels: patch

#126 fix: change email subject
  utilities/email/templates/new_reservation.js
Labels: patch
