Repository utaipei-sa/api.reserve.utsa, pull requests merged in 2024-09, with the labels that each got.

#110 feat :cicd auto build image
  .github/workflows/check-version-label.yml
  .github/workflows/docker-image.yml
  .github/workflows/tag-and-release.yml
  .github/workflows/workflow.yml
Labels: enhancement, patch

#111 fix :cicd error
  .github/workflows/docker-image.yml
Labels: bug, patch

#112 fix :cicd permission
  .github/workflows/workflow.yml
Labels: bug, patch

#108 refactor :item repository
  repositories/item_repository.js
  repositories/reserve_repository.js
  repositories/space_repository.js
  routes/reserve/get_item.js
  routes/reserve/get_item_available_time.js
  routes/reserve/get_items.js
Labels: Refactor, minor

#103 Urb 42 test post reserve
  .env.test
  package-lock.json
  package.json
  routes/reserve/index.js
  tests/post_reserve.test.js
Labels: Feature, minor

#107 Refactor API input check using express-validator
  package-lock.json
  package.json
  routes/reserve/get_item.js
  routes/reserve/get_item_available_time.js
  routes/reserve/get_space.js
  routes/reserve/get_space_available_time.js
  utilities/input_format.js
Labels: Refactor, minor
