Repository utaipei-sa/api.reserve.utsa, pull requests merged in 2025-01, with the labels that each got.

#135 Fix: HTML tag not escaped
  routes/reserve/post_reserve.js
  routes/reserve/put_reserve.js
Labels: patch

#124 build: adjust installation setting
  Dockerfile
Labels: patch

#136 Fix: prevert from reserving overlapping items
  routes/reserve/post_reserve.js
Labels: bug, patch

#141 chore: dependabot updates
  .github/dependabot.yml
Labels: Chore, patch

#147 chore(deps): update dependencies
  package-lock.json
  package.json
Labels: dependencies, patch

#152 chore: remove backend/
  backend/package-lock.json
Labels: patch

#151 Docs: Update README.md
  README.md
  README.zh-tw.md
Labels: documentation, patch

#139 Fix: prevent reservation from over a week
  routes/reserve/post_reserve.js
  utilities/reserve/validate_item_reservation.js
  utilities/reserve/validate_space_reservation.js
Labels: bug, patch

#137 Fix: prevent from reserving invalid date - `YYYY-MM-00`
  routes/reserve/post_reserve.js
Labels: bug, patch
